//! Analysis category — 11 tools, 6–14 modes each.
//! Vulnerability scanning, XSS/SQLi testing, WAF detection, SSL analysis,
//! network packet analysis, secret detection, and visual reconnaissance.
//! Bug fixes: Dalfox --deep-scan → --deep-domxss, positional URL syntax.
//! Replaced EyeWitness + Aquatone → GoWitness.
//! Removed TruffleHog (duplicate of Crawling).

use super::types::{Category, InputKind, Mode, OutputFormat, Tool};

pub static ANALYSIS: Category = Category {
    name: "Analysis",
    tools: &[
        // ── Nuclei (Template-Based Vulnerability Scanner) ────────────────
        Tool {
            name: "Nuclei",
            binary: "nuclei",
            modes: &[
                Mode {
                    name: "Full Template Scan",
                    cmd_template: "nuclei -u {url} -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Critical + High Severity",
                    cmd_template: "nuclei -u {url} -severity critical,high -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CVE Tag Scan",
                    cmd_template: "nuclei -u {url} -tags cve -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "KEV (Known Exploited Vulns)",
                    cmd_template: "nuclei -u {url} -tags kev -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Exposure & Panel Scan",
                    cmd_template: "nuclei -u {url} -tags exposure,panel -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cloud Security Scan",
                    cmd_template: "nuclei -u {url} -tags cloud,aws,azure,gcp -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "API Security Scan",
                    cmd_template: "nuclei -u {url} -tags api,graphql,swagger -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Misconfiguration Scan",
                    cmd_template: "nuclei -u {url} -tags misconfig,default-login -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Network Protocol Scan",
                    cmd_template: "nuclei -u {url} -tags network -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSONL Export Results",
                    cmd_template: "nuclei -u {url} -jsonl -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "New Templates Only",
                    cmd_template: "nuclei -u {url} -nt -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk Target Scan",
                    cmd_template: "nuclei -l {file} -severity critical,high -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Rate-Limited Safe Scan",
                    cmd_template: "nuclei -u {url} -rl 50 -c 5 -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Template Scan",
                    cmd_template: "nuclei -u {url} -t {value} -silent -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Dalfox (XSS Scanner) ─────────────────────────────────────────
        // NOTE: Fixed --deep-scan → --deep-domxss, positional URL.
        Tool {
            name: "Dalfox",
            binary: "dalfox",
            modes: &[
                Mode {
                    name: "Basic XSS Scan",
                    cmd_template: "dalfox url {url} -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Deep DOM XSS Scan",
                    cmd_template: "dalfox url {url} --deep-domxss -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Blind XSS Scan",
                    cmd_template: "dalfox url {url} -b {value} -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Results",
                    cmd_template: "dalfox url {url} --format json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk URL File Scan",
                    cmd_template: "dalfox file {file} -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline from Gau",
                    cmd_template: "gau {domain} | grep '=' | dalfox pipe -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Payload Scan",
                    cmd_template: "dalfox url {url} --custom-payload {file} -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "WAF Bypass Mode",
                    cmd_template: "dalfox url {url} --waf-evasion -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Header Auth Scan",
                    cmd_template: "dalfox url {url} -H 'Authorization: Bearer {value}' -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Follow Redirects Scan",
                    cmd_template: "dalfox url {url} --follow-redirects -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── SQLMap (SQL Injection Scanner) ────────────────────────────────
        Tool {
            name: "SQLMap",
            binary: "sqlmap",
            modes: &[
                Mode {
                    name: "Auto Detection Scan",
                    cmd_template: "sqlmap -u {url} --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Forms Auto-Detect",
                    cmd_template: "sqlmap -u {url} --forms --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Crawl + Scan",
                    cmd_template: "sqlmap -u {url} --crawl=3 --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "High Risk/Level Deep Scan",
                    cmd_template: "sqlmap -u {url} --risk=3 --level=5 --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Tamper Script Evasion",
                    cmd_template: "sqlmap -u {url} --tamper=space2comment,between --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Boolean-Based Blind",
                    cmd_template: "sqlmap -u {url} --technique=B --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Time-Based Blind",
                    cmd_template: "sqlmap -u {url} --technique=T --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Request File Scan",
                    cmd_template: "sqlmap -r {file} --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Proxy + Auth Scan",
                    cmd_template: "sqlmap -u {url} --proxy http://127.0.0.1:8080 --batch --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Wizard Mode (Interactive)",
                    cmd_template: "sqlmap --wizard --output-dir={output_file}_dir | tee {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Nikto (Web Server Scanner) ──────────────────────────────────
        Tool {
            name: "Nikto",
            binary: "nikto",
            modes: &[
                Mode {
                    name: "Full Web Scan",
                    cmd_template: "nikto -h {url} -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Tuning: Interesting Files",
                    cmd_template: "nikto -h {url} -T 1 -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Tuning: Misconfig & Default",
                    cmd_template: "nikto -h {url} -T 23 -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Tuning: Injection (XSS/SQLi)",
                    cmd_template: "nikto -h {url} -T 49 -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Evasion Mode (IDS Bypass)",
                    cmd_template: "nikto -h {url} -evasion 1 -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Scan",
                    cmd_template: "nikto -h {url} -o {output_file} -Format json",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "XML Export Scan",
                    cmd_template: "nikto -h {url} -o {output_file} -Format xml",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Xml,
                    file_ext: "xml",
                },
                Mode {
                    name: "Custom Port Scan",
                    cmd_template: "nikto -h {ip} -p {ports} -o {output_file} -Format txt",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SSL/TLS Only Scan",
                    cmd_template: "nikto -h {url} -ssl -o {output_file} -Format txt",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Plugin Specific Scan",
                    cmd_template: "nikto -h {url} -Plugins '{value}' -o {output_file} -Format txt",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Wafw00f (WAF Detection) ─────────────────────────────────────
        Tool {
            name: "Wafw00f",
            binary: "wafw00f",
            modes: &[
                Mode {
                    name: "Quick WAF Detection",
                    cmd_template: "wafw00f {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Test All WAFs",
                    cmd_template: "wafw00f {url} -a | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Verbose Detection",
                    cmd_template: "wafw00f {url} -v | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Fingerprint Only",
                    cmd_template: "wafw00f {url} -f | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Detection",
                    cmd_template: "wafw00f {url} -o {output_file} -f json",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CSV Export Detection",
                    cmd_template: "wafw00f {url} -o {output_file} -f csv",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Csv,
                    file_ext: "csv",
                },
                Mode {
                    name: "Proxy Detection",
                    cmd_template: "wafw00f {url} -p http://127.0.0.1:8080 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Header Detection",
                    cmd_template: "wafw00f {url} -H '{value}' | tee {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk URL Detection",
                    cmd_template: "wafw00f -i {file} | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "List Known WAFs",
                    cmd_template: "wafw00f -l > {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── testssl.sh (SSL/TLS Security Testing) ────────────────────────
        Tool {
            name: "testssl.sh",
            binary: "testssl",
            modes: &[
                Mode {
                    name: "Full TLS Assessment",
                    cmd_template: "testssl {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Protocol Check Only",
                    cmd_template: "testssl -p {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cipher Suite Check",
                    cmd_template: "testssl -E {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Vulnerability Check",
                    cmd_template: "testssl -U {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON File Export",
                    cmd_template: "testssl --jsonfile {output_file} {url}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "HTML Report Export",
                    cmd_template: "testssl --htmlfile {output_file} {url}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Raw,
                    file_ext: "html",
                },
                Mode {
                    name: "Certificate Details",
                    cmd_template: "testssl -S {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Heartbleed + POODLE Check",
                    cmd_template: "testssl -B -O -A {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Parallel Mass Scan",
                    cmd_template: "testssl --parallel {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Severity Filter Scan",
                    cmd_template: "testssl --severity HIGH {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── SSLScan (SSL/TLS Scanner) ────────────────────────────────────
        Tool {
            name: "SSLScan",
            binary: "sslscan",
            modes: &[
                Mode {
                    name: "Full SSL/TLS Scan",
                    cmd_template: "sslscan {domain} | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "No Colour Output",
                    cmd_template: "sslscan --no-colour {domain} > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "TLS 1.3 Only Check",
                    cmd_template: "sslscan --tls13 {domain} | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "STARTTLS SMTP Scan",
                    cmd_template: "sslscan --starttls-smtp {domain}:25 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "STARTTLS FTP Scan",
                    cmd_template: "sslscan --starttls-ftp {domain}:21 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "STARTTLS IMAP Scan",
                    cmd_template: "sslscan --starttls-imap {domain}:143 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "XML Export Scan",
                    cmd_template: "sslscan --xml={output_file} {domain}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Xml,
                    file_ext: "xml",
                },
                Mode {
                    name: "Cipher Preference Scan",
                    cmd_template: "sslscan --show-ciphers {domain} | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Port TLS Scan",
                    cmd_template: "sslscan {domain}:{ports} | tee {output_file}",
                    inputs: &[InputKind::Domain, InputKind::Ports],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SNI Specific Scan",
                    cmd_template: "sslscan --sni-name={value} {domain} | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── tcpdump (Network Packet Capture) ─────────────────────────────
        Tool {
            name: "tcpdump",
            binary: "tcpdump",
            modes: &[
                Mode {
                    name: "HTTP Traffic Capture",
                    cmd_template: "timeout 30 tcpdump -i any port 80 or port 443 -w {output_file} -c 1000",
                    inputs: &[],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
                Mode {
                    name: "DNS Traffic Capture",
                    cmd_template: "timeout 30 tcpdump -i any port 53 -w {output_file} -c 500",
                    inputs: &[],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
                Mode {
                    name: "Host-Specific Capture",
                    cmd_template: "timeout 30 tcpdump -i any host {ip} -w {output_file} -c 1000",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
                Mode {
                    name: "Verbose Decode Capture",
                    cmd_template: "timeout 30 tcpdump -i any -vvv -A -c 500 2>&1 | tee {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SYN Packets Only",
                    cmd_template: "timeout 30 tcpdump -i any 'tcp[tcpflags] & (tcp-syn) != 0' -c 500 -w {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
                Mode {
                    name: "Port-Specific Capture",
                    cmd_template: "timeout 30 tcpdump -i any port {ports} -w {output_file} -c 1000",
                    inputs: &[InputKind::Ports],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
            ],
        },
        // ── tshark (Network Protocol Analyzer) ──────────────────────────
        Tool {
            name: "tshark",
            binary: "tshark",
            modes: &[
                Mode {
                    name: "HTTP Request Analysis",
                    cmd_template: "tshark -r {file} -Y 'http.request' -T fields -e ip.src -e http.host -e http.request.uri > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "DNS Query Extraction",
                    cmd_template: "tshark -r {file} -Y 'dns.qry.name' -T fields -e dns.qry.name | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "TLS Handshake Analysis",
                    cmd_template: "tshark -r {file} -Y 'tls.handshake' -T fields -e ip.src -e ip.dst -e tls.handshake.extensions_server_name > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Conversation Statistics",
                    cmd_template: "tshark -r {file} -q -z conv,tcp > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Credential Capture (HTTP)",
                    cmd_template: "tshark -r {file} -Y 'http.authbasic or http.request.method==POST' -T fields -e ip.src -e http.authbasic -e http.file_data > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Protocol Hierarchy Stats",
                    cmd_template: "tshark -r {file} -q -z io,phs > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Packets",
                    cmd_template: "tshark -r {file} -T json > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Live Capture (30s)",
                    cmd_template: "timeout 30 tshark -i any -c 500 -w {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Raw,
                    file_ext: "pcap",
                },
            ],
        },
        // ── Gitleaks (Git Secret Scanner) ────────────────────────────────
        Tool {
            name: "Gitleaks",
            binary: "gitleaks",
            modes: &[
                Mode {
                    name: "Detect Secrets (Directory)",
                    cmd_template: "gitleaks detect -s {value} -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Detect Secrets (Git Repo)",
                    cmd_template: "gitleaks detect -s {value} --log-opts='--all' -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Verbose Detection",
                    cmd_template: "gitleaks detect -s {value} -v -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Baseline Comparison",
                    cmd_template: "gitleaks detect -s {value} --baseline-path {file} -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CI Pipeline Mode",
                    cmd_template: "gitleaks detect -s {value} --exit-code 1 -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Config File",
                    cmd_template: "gitleaks detect -s {value} --config {file} -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Pre-Commit Staged Check",
                    cmd_template: "gitleaks protect -s {value} --staged -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CSV Export Results",
                    cmd_template: "gitleaks detect -s {value} -f csv -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Csv,
                    file_ext: "csv",
                },
                Mode {
                    name: "SARIF Export Results",
                    cmd_template: "gitleaks detect -s {value} -f sarif -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Raw,
                    file_ext: "sarif",
                },
                Mode {
                    name: "No Git Scan (Files Only)",
                    cmd_template: "gitleaks detect -s {value} --no-git -r {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── GoWitness (Web Screenshot & Visual Recon) ────────────────────
        // Replaces EyeWitness (poorly maintained) and Aquatone (abandoned).
        Tool {
            name: "GoWitness",
            binary: "gowitness",
            modes: &[
                Mode {
                    name: "Single URL Screenshot",
                    cmd_template: "gowitness scan single --url {url} --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Batch URL Screenshot",
                    cmd_template: "gowitness scan file --file {file} --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Nmap XML Import",
                    cmd_template: "gowitness scan nmap --file {file} --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Timeout Screenshot",
                    cmd_template: "gowitness scan single --url {url} --timeout 15 --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom User-Agent Scan",
                    cmd_template: "gowitness scan single --url {url} --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Proxy Mode Screenshot",
                    cmd_template: "gowitness scan single --url {url} --proxy http://127.0.0.1:8080 --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Full-Page Screenshot",
                    cmd_template: "gowitness scan single --url {url} --fullpage --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Resolution Scan",
                    cmd_template: "gowitness scan single --url {url} --resolution 1920x1080 --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Subfinder → Shots",
                    cmd_template: "subfinder -d {domain} -all -silent | httpx-pd -silent | gowitness scan file --file /dev/stdin --screenshot-path /tmp/gowitness/ 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Report Listing",
                    cmd_template: "gowitness report list 2>&1 | tee {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
    ],
};