//! Automation category — 14 tools, 6–12 modes each.
//! Workflow automation, URL manipulation, pattern matching, data processing,
//! and pipeline utilities.
//! Removed tmux (not a recon tool) and wget (redundant with curl).
//! Added Notify (pipeline notifications) and Interactsh (OOB testing).

use super::types::{Category, InputKind, Mode, OutputFormat, Tool};

pub static AUTOMATION: Category = Category {
    name: "Automation",
    tools: &[
        // ── BBOT (Automation Framework) ──────────────────────────────────
        Tool {
            name: "BBOT",
            binary: "bbot",
            modes: &[
                Mode {
                    name: "Full Scan (All Modules)",
                    cmd_template: "bbot -t {domain} -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Subdomain Enumeration",
                    cmd_template: "bbot -t {domain} -p subdomain-enum -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Web Spider Preset",
                    cmd_template: "bbot -t {domain} -p spider -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cloud Enumeration",
                    cmd_template: "bbot -t {domain} -p cloud-enum -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Web Basic Scan",
                    cmd_template: "bbot -t {domain} -p web-basic -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Specific Module Scan",
                    cmd_template: "bbot -t {domain} -m {value} -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Output Scan",
                    cmd_template: "bbot -t {domain} -p subdomain-enum -om json -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Aggressive Full Recon",
                    cmd_template: "bbot -t {domain} -f aggressive -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Passive Only Scan",
                    cmd_template: "bbot -t {domain} -f passive -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Config Scan",
                    cmd_template: "bbot -t {domain} -c {file} -o /tmp/bbot_{timestamp} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── ReconFTW (Automated Reconnaissance) ─────────────────────────
        Tool {
            name: "ReconFTW",
            binary: "reconftw.sh",
            modes: &[
                Mode {
                    name: "Full Recon Pipeline",
                    cmd_template: "reconftw.sh -d {domain} -a 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Subdomain Enum Only",
                    cmd_template: "reconftw.sh -d {domain} -s 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "OSINT Intelligence",
                    cmd_template: "reconftw.sh -d {domain} --osint 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Vulnerability Scan",
                    cmd_template: "reconftw.sh -d {domain} --vulns 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Multi-Target Scan",
                    cmd_template: "reconftw.sh -l {file} -a 2>&1 | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Web Fuzzing Only",
                    cmd_template: "reconftw.sh -d {domain} -w 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Config Scan",
                    cmd_template: "reconftw.sh -d {domain} -a --config {file} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Port Scanning Only",
                    cmd_template: "reconftw.sh -d {domain} -p 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Google Dorking",
                    cmd_template: "reconftw.sh -d {domain} -g 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Resume Previous Scan",
                    cmd_template: "reconftw.sh -d {domain} --resume 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Osmedeus (Automated Workflow Engine) ─────────────────────────
        Tool {
            name: "Osmedeus",
            binary: "osmedeus",
            modes: &[
                Mode {
                    name: "General Scan Workflow",
                    cmd_template: "osmedeus scan -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Fast Subdomain Workflow",
                    cmd_template: "osmedeus scan -f fast -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Vulnerability Workflow",
                    cmd_template: "osmedeus scan -f vuln -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CIDR Network Scan",
                    cmd_template: "osmedeus scan -f cidr -t {ip}/24 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Workflow Scan",
                    cmd_template: "osmedeus scan -f {value} -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Multi-Target File Scan",
                    cmd_template: "osmedeus scan -T {file} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Resume Previous Scan",
                    cmd_template: "osmedeus scan --resume -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cloud Provider Scan",
                    cmd_template: "osmedeus provider scan -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Report Generation",
                    cmd_template: "osmedeus report -t {domain} 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "List Available Workflows",
                    cmd_template: "osmedeus scan -lf 2>&1 | tee {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Sn1per (Automated Pentest Framework) ─────────────────────────
        Tool {
            name: "Sn1per",
            binary: "sniper",
            modes: &[
                Mode {
                    name: "Normal Recon Scan",
                    cmd_template: "sniper -t {domain} -m normal 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Stealth Recon Scan",
                    cmd_template: "sniper -t {domain} -m stealth 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Discover Mode",
                    cmd_template: "sniper -t {domain} -m discover 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Port Scan Mode",
                    cmd_template: "sniper -t {domain} -m port 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Vulnerability Mode",
                    cmd_template: "sniper -t {domain} -m vulns 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Brute Force Mode",
                    cmd_template: "sniper -t {domain} -m bruteforce 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Loot Collection",
                    cmd_template: "sniper -t {domain} -m loot 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Web Application Scan",
                    cmd_template: "sniper -t {url} -m web 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "OSINT Mode",
                    cmd_template: "sniper -t {domain} -m osint 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP Target Scan",
                    cmd_template: "sniper -t {ip} -m normal 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Unfurl (URL Parsing & Decomposition) ─────────────────────────
        Tool {
            name: "Unfurl",
            binary: "unfurl",
            modes: &[
                Mode {
                    name: "Extract Domains",
                    cmd_template: "cat {file} | unfurl domains | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extract Paths",
                    cmd_template: "cat {file} | unfurl paths | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extract Apex Domains",
                    cmd_template: "cat {file} | unfurl apexes | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extract Keys (Params)",
                    cmd_template: "cat {file} | unfurl keys | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extract Values",
                    cmd_template: "cat {file} | unfurl values | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Format String",
                    cmd_template: "cat {file} | unfurl format '{value}' | sort -u > {output_file}",
                    inputs: &[InputKind::File, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export URLs",
                    cmd_template: "cat {file} | unfurl json > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Extract Unique Params",
                    cmd_template: "cat {file} | unfurl keypairs | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Gau → Unfurl",
                    cmd_template: "gau {domain} | unfurl domains | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Wayback → Paths",
                    cmd_template: "echo {domain} | waybackurls | unfurl paths | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Anew (Line Deduplication Utility) ────────────────────────────
        Tool {
            name: "Anew",
            binary: "anew",
            modes: &[
                Mode {
                    name: "Deduplicate to File",
                    cmd_template: "cat {file} | anew {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Quiet Mode (New Only)",
                    cmd_template: "cat {file} | anew -q {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Subfinder → Anew",
                    cmd_template: "subfinder -d {domain} -all -silent | anew {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Gau → Anew",
                    cmd_template: "gau {domain} | anew {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Katana → Anew",
                    cmd_template: "katana -u {url} -d 3 -jc -silent | anew {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Dry Run (Show Diff)",
                    cmd_template: "cat {file} | anew -d {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── GF (Pattern-Based URL Filtering) ─────────────────────────────
        Tool {
            name: "GF",
            binary: "gf",
            modes: &[
                Mode {
                    name: "XSS Pattern Match",
                    cmd_template: "cat {file} | gf xss | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SQLi Pattern Match",
                    cmd_template: "cat {file} | gf sqli | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SSRF Pattern Match",
                    cmd_template: "cat {file} | gf ssrf | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "LFI Pattern Match",
                    cmd_template: "cat {file} | gf lfi | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "RCE Pattern Match",
                    cmd_template: "cat {file} | gf rce | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IDOR Pattern Match",
                    cmd_template: "cat {file} | gf idor | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Redirect Pattern Match",
                    cmd_template: "cat {file} | gf redirect | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SSTI Pattern Match",
                    cmd_template: "cat {file} | gf ssti | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Debug Pages Pattern",
                    cmd_template: "cat {file} | gf debug-pages | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Interesting Params",
                    cmd_template: "cat {file} | gf interestingparams | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Gau → GF All",
                    cmd_template: "gau {domain} | gf xss sqli ssrf lfi | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Upload Fields Pattern",
                    cmd_template: "cat {file} | gf upload-fields | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── URO (URL Deduplication & Filtering) ──────────────────────────
        Tool {
            name: "URO",
            binary: "uro",
            modes: &[
                Mode {
                    name: "Basic URL Dedup",
                    cmd_template: "cat {file} | uro > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Filter by Extension",
                    cmd_template: "cat {file} | uro -f hasext | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Filter Has Params",
                    cmd_template: "cat {file} | uro -f hasparams | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Remove Duplicates",
                    cmd_template: "cat {file} | uro -f vuln | sort -u > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Gau → URO",
                    cmd_template: "gau {domain} | uro > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Katana → URO",
                    cmd_template: "katana -u {url} -d 3 -jc -silent | uro > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Wayback → URO",
                    cmd_template: "echo {domain} | waybackurls | uro > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Whitelist Extensions",
                    cmd_template: "cat {file} | uro -w {value} > {output_file}",
                    inputs: &[InputKind::File, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── jq (JSON Processing) ─────────────────────────────────────────
        Tool {
            name: "jq",
            binary: "jq",
            modes: &[
                Mode {
                    name: "Pretty Print JSON",
                    cmd_template: "jq '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Extract Keys",
                    cmd_template: "jq 'keys' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Flatten Array",
                    cmd_template: "jq '.[]' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom JQ Filter",
                    cmd_template: "jq '{value}' {file} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Extract Nuclei Findings",
                    cmd_template: "jq -r '.info.name + \" | \" + .host' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extract HTTPX Hosts",
                    cmd_template: "jq -r '.url' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Select by Field",
                    cmd_template: "jq 'select(.{value})' {file} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "JSONL to JSON Array",
                    cmd_template: "jq -s '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── yq (YAML/XML Processing) ─────────────────────────────────────
        Tool {
            name: "yq",
            binary: "yq",
            modes: &[
                Mode {
                    name: "Pretty Print YAML",
                    cmd_template: "yq '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Raw,
                    file_ext: "yaml",
                },
                Mode {
                    name: "Convert YAML → JSON",
                    cmd_template: "yq -o json '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Convert JSON → YAML",
                    cmd_template: "yq -P '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Raw,
                    file_ext: "yaml",
                },
                Mode {
                    name: "Custom YQ Filter",
                    cmd_template: "yq '{value}' {file} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Raw,
                    file_ext: "yaml",
                },
                Mode {
                    name: "K8s Config Parser",
                    cmd_template: "yq '.metadata' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Raw,
                    file_ext: "yaml",
                },
                Mode {
                    name: "Multi-Document Split",
                    cmd_template: "yq -s '\"doc_\" + $index' {file} && echo 'Documents split' > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Merge YAML Files",
                    cmd_template: "yq eval-all '. as $item ireduce ({{}}; . * $item)' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Raw,
                    file_ext: "yaml",
                },
                Mode {
                    name: "Convert XML → JSON",
                    cmd_template: "yq -p xml -o json '.' {file} > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── Ripgrep (Pattern Search) ─────────────────────────────────────
        Tool {
            name: "Ripgrep",
            binary: "rg",
            modes: &[
                Mode {
                    name: "API Key Pattern Search",
                    cmd_template: "rg -i '(api[_-]?key|apikey|api[_-]?secret)\\s*[:=]\\s*[\"\\x27]?[a-zA-Z0-9]{{16,}}' {value} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JWT Token Discovery",
                    cmd_template: "rg -o 'eyJ[a-zA-Z0-9_-]*\\.eyJ[a-zA-Z0-9_-]*\\.[a-zA-Z0-9_-]*' {value} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "URL Extraction",
                    cmd_template: "rg -o 'https?://[^ \"<>]+' {value} | sort -u > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "S3 Bucket Discovery",
                    cmd_template: "rg -io '[a-zA-Z0-9.-]+\\.s3[a-zA-Z0-9.-]*\\.amazonaws\\.com' {value} | sort -u > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cloud Metadata URL",
                    cmd_template: "rg -i '169\\.254\\.169\\.254|metadata\\.google|metadata\\.azure' {value} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Secret Pattern Search",
                    cmd_template: "rg -i '(password|passwd|secret|token|private[_-]?key)\\s*[:=]' {value} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Email Extraction",
                    cmd_template: "rg -o '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{{2,}}' {value} | sort -u > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP Address Extraction",
                    cmd_template: "rg -o '\\b\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}\\b' {value} | sort -u > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Regex Search",
                    cmd_template: "rg '{value}' {file} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Count Matches",
                    cmd_template: "rg -c '{value}' {file} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Curl (HTTP Request Utility) ──────────────────────────────────
        Tool {
            name: "Curl",
            binary: "curl",
            modes: &[
                Mode {
                    name: "Full Response Dump",
                    cmd_template: "curl -sS -D - {url} > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Headers Only",
                    cmd_template: "curl -sS -I {url} > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON API GET Request",
                    cmd_template: "curl -sS -H 'Accept: application/json' {url} | jq '.' > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "JSON API POST Request",
                    cmd_template: "curl -sS -X POST -H 'Content-Type: application/json' -d '{value}' {url} | jq '.' > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Cookie Extraction",
                    cmd_template: "curl -sS -c - {url} > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "TLS Certificate Info",
                    cmd_template: "curl -svvv --head {url} 2>&1 | grep -E '(subject:|issuer:|expire|SSL)' > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Timing Analysis",
                    cmd_template: "curl -sS -o /dev/null -w 'DNS: %{{time_namelookup}}s\\nConnect: %{{time_connect}}s\\nTLS: %{{time_appconnect}}s\\nStart: %{{time_starttransfer}}s\\nTotal: %{{time_total}}s\\nSize: %{{size_download}} bytes\\n' {url} > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Follow Redirects Chain",
                    cmd_template: "curl -sS -L -D - -o /dev/null {url} > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Header Request",
                    cmd_template: "curl -sS -H '{value}' {url} > {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Security Headers Check",
                    cmd_template: "curl -sS -I {url} | grep -iE '(strict-transport|content-security|x-frame|x-content|x-xss|referrer|permissions)' > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Notify (Pipeline Notification Engine) ────────────────────────
        Tool {
            name: "Notify",
            binary: "notify",
            modes: &[
                Mode {
                    name: "Send File Notifications",
                    cmd_template: "cat {file} | notify -bulk -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Send Single Message",
                    cmd_template: "echo '{value}' | notify -o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Slack Provider Only",
                    cmd_template: "cat {file} | notify -provider slack -bulk -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Discord Provider Only",
                    cmd_template: "cat {file} | notify -provider discord -bulk -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Telegram Provider Only",
                    cmd_template: "cat {file} | notify -provider telegram -bulk -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Nuclei → Notify",
                    cmd_template: "nuclei -l {file} -severity critical,high -silent | notify -bulk -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Subfinder → Notify",
                    cmd_template: "subfinder -d {domain} -all -silent | notify -bulk -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Config Notify",
                    cmd_template: "cat {file} | notify -provider-config {value} -bulk -o {output_file}",
                    inputs: &[InputKind::File, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Interactsh (OOB Interaction Server) ──────────────────────────
        Tool {
            name: "Interactsh",
            binary: "interactsh-client",
            modes: &[
                Mode {
                    name: "Generate OOB URL",
                    cmd_template: "interactsh-client -json -o {output_file} -n 1",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Long-Running Listener",
                    cmd_template: "timeout 120 interactsh-client -json -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Server URL",
                    cmd_template: "interactsh-client -server {value} -json -o {output_file} -n 1",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Verbose Mode Listener",
                    cmd_template: "timeout 120 interactsh-client -v -json -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Multiple URLs Generate",
                    cmd_template: "interactsh-client -json -o {output_file} -n 5",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Poll Interval Control",
                    cmd_template: "timeout 120 interactsh-client -json -o {output_file} -poll-interval 3",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Auth Token Mode",
                    cmd_template: "interactsh-client -token {value} -json -o {output_file} -n 1",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "DNS Only Interaction",
                    cmd_template: "timeout 120 interactsh-client -dns-only -json -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
    ],
};