//! Crawling category — 9 tools, 10–12 modes each.
//! Web crawling, URL discovery, content fuzzing, parameter mining, and secret scanning.
//! Nuclei removed (duplicate of Analysis category).
//! GoSpider added as modern web spider.
//! TruffleHog {path} placeholder bug fixed → {value}.

use super::types::{Category, InputKind, Mode, OutputFormat, Tool};

pub static CRAWLING: Category = Category {
    name: "Crawling",
    tools: &[
        // ── Katana (High-Performance Web Crawler) ────────────────────────
        Tool {
            name: "Katana",
            binary: "katana",
            modes: &[
                Mode {
                    name: "Standard Crawl",
                    cmd_template: "katana -u {url} -d 3 -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JS Crawl + Parsing",
                    cmd_template: "katana -u {url} -d 3 -jc -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSLuice Deep JS Parsing",
                    cmd_template: "katana -u {url} -d 3 -jc -jsl -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Headless SPA Crawl",
                    cmd_template: "katana -u {url} -d 3 -hl -jc -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Auto Form Fill + Headless",
                    cmd_template: "katana -u {url} -d 3 -hl -aff -jc -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Field Extraction (URLs)",
                    cmd_template: "katana -u {url} -d 3 -f url -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Scope Regex",
                    cmd_template: "katana -u {url} -d 3 -fs rdn -jc -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export with Metadata",
                    cmd_template: "katana -u {url} -d 3 -jc -json -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Passive Crawl (No Active)",
                    cmd_template: "katana -u {url} -d 3 -ps -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk URL Crawl",
                    cmd_template: "katana -list {file} -d 3 -jc -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → GF Patterns",
                    cmd_template: "katana -u {url} -d 3 -jc -silent | gf xss | sort -u > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Extension Filter Crawl",
                    cmd_template: "katana -u {url} -d 3 -jc -ef png,jpg,gif,css,svg,woff,ico -silent -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Gau (Passive URL Discovery from Archives) ───────────────────
        Tool {
            name: "Gau",
            binary: "gau",
            modes: &[
                Mode {
                    name: "All URL Discovery",
                    cmd_template: "gau {domain} --o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Include Subdomains",
                    cmd_template: "gau --subs {domain} --o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Wayback Provider Only",
                    cmd_template: "gau --providers wayback {domain} --o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Multi-Provider Discovery",
                    cmd_template: "gau --providers wayback,commoncrawl,otx,urlscan {domain} --o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Date-Range URL Fetch",
                    cmd_template: "gau --from {value} {domain} --o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value"), InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Output Discovery",
                    cmd_template: "gau --json {domain} --o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Domain Fetch",
                    cmd_template: "cat {file} | gau --o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Validate",
                    cmd_template: "gau {domain} | httpx-pd -silent -sc -title -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → GF XSS Patterns",
                    cmd_template: "gau {domain} | gf xss | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → URO Deduplicate",
                    cmd_template: "gau --subs {domain} | uro | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Waybackurls (Archive URL Retrieval) ──────────────────────────
        Tool {
            name: "Waybackurls",
            binary: "waybackurls",
            modes: &[
                Mode {
                    name: "Full URL Retrieval",
                    cmd_template: "echo {domain} | waybackurls > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "No Subdomains",
                    cmd_template: "echo {domain} | waybackurls -no-subs > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "With Timestamps",
                    cmd_template: "echo {domain} | waybackurls -dates > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Unique Paths Only",
                    cmd_template: "echo {domain} | waybackurls | unfurl paths | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JS Files Only",
                    cmd_template: "echo {domain} | waybackurls | grep '\\.js$' | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Parameters Only",
                    cmd_template: "echo {domain} | waybackurls | grep '?' | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk Domain Retrieval",
                    cmd_template: "cat {file} | waybackurls > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Alive",
                    cmd_template: "echo {domain} | waybackurls | httpx-pd -silent -sc -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → GF SSRF",
                    cmd_template: "echo {domain} | waybackurls | gf ssrf | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "API Endpoints Only",
                    cmd_template: "echo {domain} | waybackurls | grep -iE '(/api/|/v[0-9]+/|/graphql|/rest/)' | sort -u > {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── GoSpider (Fast Web Spider) ───────────────────────────────────
        Tool {
            name: "GoSpider",
            binary: "gospider",
            modes: &[
                Mode {
                    name: "Standard Spider",
                    cmd_template: "gospider -s {url} -d 3 -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Deep JS + Sitemap Spider",
                    cmd_template: "gospider -s {url} -d 5 --js --sitemap --robots -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Include Subdomains",
                    cmd_template: "gospider -s {url} -d 3 --include-subs -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Include Other Sources",
                    cmd_template: "gospider -s {url} -d 3 -a -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Concurrent Threads Spider",
                    cmd_template: "gospider -s {url} -d 3 -c 20 -t 10 -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Blacklist Extensions",
                    cmd_template: "gospider -s {url} -d 3 --blacklist png,jpg,gif,css,svg,woff -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Spider",
                    cmd_template: "gospider -s {url} -d 3 --json -q | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk URL Spider",
                    cmd_template: "gospider -S {file} -d 3 -q | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Cookie Auth Spider",
                    cmd_template: "gospider -s {url} -d 3 --cookie '{value}' -q | tee {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → GF Patterns",
                    cmd_template: "gospider -s {url} -d 3 --js -q | grep -oP 'https?://[^ ]+' | sort -u | gf xss > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── XnLinkFinder (Endpoint & Parameter Extraction) ──────────────
        Tool {
            name: "XnLinkFinder",
            binary: "xnLinkFinder",
            modes: &[
                Mode {
                    name: "URL Endpoint Discovery",
                    cmd_template: "xnLinkFinder -i {url} -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Deep Crawl Discovery",
                    cmd_template: "xnLinkFinder -i {url} -d 5 -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Scope-Restricted Discovery",
                    cmd_template: "xnLinkFinder -i {url} -sf {domain} -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cookie-Based Auth Crawl",
                    cmd_template: "xnLinkFinder -i {url} -c '{value}' -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Header Crawl",
                    cmd_template: "xnLinkFinder -i {url} -H '{value}' -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Parameters Only Extraction",
                    cmd_template: "xnLinkFinder -i {url} -op {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk URL File Discovery",
                    cmd_template: "xnLinkFinder -i {file} -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Regex Pattern",
                    cmd_template: "xnLinkFinder -i {url} -regex '{value}' -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Exclude Extension Filter",
                    cmd_template: "xnLinkFinder -i {url} -ex png,jpg,gif,css,svg -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Validate",
                    cmd_template: "xnLinkFinder -i {url} | httpx-pd -silent -sc -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Arjun (HTTP Parameter Discovery) ─────────────────────────────
        Tool {
            name: "Arjun",
            binary: "arjun",
            modes: &[
                Mode {
                    name: "GET Parameter Discovery",
                    cmd_template: "arjun -u {url} -m GET -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "POST Parameter Discovery",
                    cmd_template: "arjun -u {url} -m POST -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Body Parameter",
                    cmd_template: "arjun -u {url} -m JSON -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "XML Body Parameter",
                    cmd_template: "arjun -u {url} -m XML -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Results",
                    cmd_template: "arjun -u {url} -m GET -oJ {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Wordlist Scan",
                    cmd_template: "arjun -u {url} -w {file} -oT {output_file}",
                    inputs: &[InputKind::Url, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Header Auth Scan",
                    cmd_template: "arjun -u {url} --headers '{value}' -oT {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Rate-Limited Scan",
                    cmd_template: "arjun -u {url} -m GET --stable -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk URL File Scan",
                    cmd_template: "arjun -i {file} -m GET -oT {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Concurrent Threads Scan",
                    cmd_template: "arjun -u {url} -m GET -t 10 -oT {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── FFUF (Web Fuzzer) ────────────────────────────────────────────
        Tool {
            name: "FFUF",
            binary: "ffuf",
            modes: &[
                Mode {
                    name: "Directory Discovery",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -u {url}/FUZZ -mc 200,301,302,403 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "File Discovery",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-files.txt -u {url}/FUZZ -mc 200,301,302,403 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Recursive Fuzzing",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -u {url}/FUZZ -mc 200,301,302,403 -recursion -recursion-depth 2 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "API Endpoint Fuzzing",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt -u {url}/FUZZ -mc 200,201,204,301,302,401,403 -H 'Content-Type: application/json' -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Subdomain VHOST Fuzzing",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -u {url} -H 'Host: FUZZ.{domain}' -mc 200 -of json -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Header Fuzzing",
                    cmd_template: "ffuf -w {file} -u {url} -H '{value}: FUZZ' -mc all -fc 400 -of json -o {output_file}",
                    inputs: &[InputKind::File, InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Auth Bearer Token Fuzz",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -u {url}/FUZZ -H 'Authorization: Bearer {value}' -mc 200,201,301,302 -of json -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Wordlist Fuzz",
                    cmd_template: "ffuf -w {file} -u {url}/FUZZ -mc 200,301,302,403 -of json -o {output_file}",
                    inputs: &[InputKind::File, InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Response Size Filter",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -u {url}/FUZZ -mc all -fs {value} -of json -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Rate-Limited Fuzz",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -u {url}/FUZZ -mc 200,301,302,403 -rate 50 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "POST Data Fuzzing",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt -u {url} -X POST -d 'FUZZ=test' -mc 200,302 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Extension Fuzzing",
                    cmd_template: "ffuf -w /usr/share/seclists/Discovery/Web-Content/web-extensions.txt -u {url}/indexFUZZ -mc 200,301,302 -of json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── Feroxbuster (Content Discovery & Directory Bruteforce) ───────
        Tool {
            name: "Feroxbuster",
            binary: "feroxbuster",
            modes: &[
                Mode {
                    name: "Standard Discovery",
                    cmd_template: "feroxbuster -u {url} -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Smart Mode (Auto-Tune)",
                    cmd_template: "feroxbuster -u {url} --smart -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Thorough Mode (Deep)",
                    cmd_template: "feroxbuster -u {url} --thorough -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Scan",
                    cmd_template: "feroxbuster -u {url} --json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Wordlist Scan",
                    cmd_template: "feroxbuster -u {url} -w {file} -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Recursive with Extensions",
                    cmd_template: "feroxbuster -u {url} -x php,asp,aspx,jsp,html,js -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Collect Extensions Discovery",
                    cmd_template: "feroxbuster -u {url} --collect-extensions --auto-tune -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Status Code Filter",
                    cmd_template: "feroxbuster -u {url} -C 404,500,502 -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Rate-Limited Scan",
                    cmd_template: "feroxbuster -u {url} --rate-limit 50 --scan-limit 1 -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Proxy Mode Scan",
                    cmd_template: "feroxbuster -u {url} --proxy http://127.0.0.1:8080 -k -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Auth Header Scan",
                    cmd_template: "feroxbuster -u {url} -H 'Authorization: Bearer {value}' -o {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Depth-Limited Scan",
                    cmd_template: "feroxbuster -u {url} -d 5 --no-recursion -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── TruffleHog (Secret & Credential Scanning) ────────────────────
        // NOTE: {path} placeholder fixed → {value} (FreeText)
        Tool {
            name: "TruffleHog",
            binary: "trufflehog",
            modes: &[
                Mode {
                    name: "Git Repo Secret Scan",
                    cmd_template: "trufflehog git {url} --json | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Verified Secrets Only",
                    cmd_template: "trufflehog git {url} --results=verified --json | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "GitHub Org Scan",
                    cmd_template: "trufflehog github --org {value} --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "File System Secret Scan",
                    cmd_template: "trufflehog filesystem {value} --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Docker Image Scan",
                    cmd_template: "trufflehog docker --image {value} --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "S3 Bucket Scan",
                    cmd_template: "trufflehog s3 --bucket {value} --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "GitLab Org Scan",
                    cmd_template: "trufflehog gitlab --org {value} --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CI Pipeline Mode (--fail)",
                    cmd_template: "trufflehog git {url} --results=verified --fail --json | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Include Comments Scan",
                    cmd_template: "trufflehog github --org {value} --issue-comments --pr-comments --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Specific Detectors Only",
                    cmd_template: "trufflehog git {url} --include-detectors {value} --json | tee {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Since Commit Scan (CI)",
                    cmd_template: "trufflehog git {url} --since-commit {value} --json | tee {output_file}",
                    inputs: &[InputKind::Url, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Verified + GitHub Issues",
                    cmd_template: "trufflehog github --org {value} --results=verified --issue-comments --json | tee {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
    ],
};