//! Discovery category — 4 tools, 10–12 modes each.
//! Focused subdomain enumeration and passive/active discovery.
//! Duplicates removed — DNS resolution, port scanning, web probing, etc.
//! live in Mapping; URL/crawling tools live in Crawling.

use super::types::{Category, InputKind, Mode, OutputFormat, Tool};

pub static DISCOVERY: Category = Category {
    name: "Discovery",
    tools: &[
        // ── Subfinder (Passive Subdomain Enumeration) ─────────────────────
        Tool {
            name: "Subfinder",
            binary: "subfinder",
            modes: &[
                Mode {
                    name: "Passive Subdomain Enum",
                    cmd_template: "subfinder -d {domain} -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "All Sources Enum",
                    cmd_template: "subfinder -d {domain} -all -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Recursive Subdomain Enum",
                    cmd_template: "subfinder -d {domain} -recursive -all -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Active + Wildcard Filter",
                    cmd_template: "subfinder -d {domain} -all -nW -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Specific Sources Enum",
                    cmd_template: "subfinder -d {domain} -sources shodan,censys,virustotal,crtsh,github -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Source Collection JSON",
                    cmd_template: "subfinder -d {domain} -all -oJ -cs -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Exclude Sources Enum",
                    cmd_template: "subfinder -d {domain} -all -es {value} -silent -o {output_file}",
                    inputs: &[InputKind::Domain, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP Resolution Output",
                    cmd_template: "subfinder -d {domain} -all -nW -oI -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk Domain Scan",
                    cmd_template: "subfinder -dL {file} -all -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Probe",
                    cmd_template: "subfinder -d {domain} -all -silent | httpx-pd -silent -sc -title -tech-detect -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → DNSX Resolve",
                    cmd_template: "subfinder -d {domain} -all -silent | dnsx -silent -a -resp -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Match Regex Filter",
                    cmd_template: "subfinder -d {domain} -all -silent -m {value} -o {output_file}",
                    inputs: &[InputKind::Domain, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Amass (Comprehensive Subdomain Enumeration) ───────────────────
        Tool {
            name: "Amass",
            binary: "amass",
            modes: &[
                Mode {
                    name: "Passive Enum",
                    cmd_template: "amass enum -passive -d {domain} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Active Enum",
                    cmd_template: "amass enum -active -d {domain} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Brute Force Enum",
                    cmd_template: "amass enum -brute -d {domain} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Active + Brute Force",
                    cmd_template: "amass enum -active -brute -d {domain} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Whois Intelligence",
                    cmd_template: "amass intel -whois -d {domain} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "ASN Intelligence",
                    cmd_template: "amass intel -asn {value} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Config-Based Scan",
                    cmd_template: "amass enum -d {domain} -config {file} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Output",
                    cmd_template: "amass enum -d {domain} -json {output_file} -nocolor 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Domain Enum",
                    cmd_template: "amass enum -df {file} -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Verbose Debug Enum",
                    cmd_template: "amass enum -d {domain} -v -nocolor > {output_file} 2>&1",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Findomain (Fast Subdomain Enumeration) ────────────────────────
        Tool {
            name: "Findomain",
            binary: "findomain",
            modes: &[
                Mode {
                    name: "Basic Subdomain Scan",
                    cmd_template: "findomain -t {domain} -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Resolve Subdomains",
                    cmd_template: "findomain -t {domain} -r -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "All APIs Aggressive Scan",
                    cmd_template: "findomain -t {domain} -a -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Quiet Mode Scan",
                    cmd_template: "findomain -t {domain} -q -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CSV Export",
                    cmd_template: "findomain -t {domain} --csv -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Csv,
                    file_ext: "csv",
                },
                Mode {
                    name: "Bulk Domain Scan",
                    cmd_template: "findomain -f {file} -u {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Monitoring Mode",
                    cmd_template: "findomain -t {domain} -m -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Resolvers",
                    cmd_template: "findomain -t {domain} -r --resolvers {file} -u {output_file}",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Check",
                    cmd_template: "findomain -t {domain} -q | httpx-pd -silent -sc -title -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP + Port Discovery",
                    cmd_template: "findomain -t {domain} -r -a -u {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── PureDNS (DNS Bruteforce + Wildcard Detection) ─────────────────
        Tool {
            name: "PureDNS",
            binary: "puredns",
            modes: &[
                Mode {
                    name: "Subdomain Bruteforce",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Deep Bruteforce (110k)",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-110000.txt {domain} -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Wordlist Bruteforce",
                    cmd_template: "puredns bruteforce {file} {domain} -w {output_file}",
                    inputs: &[InputKind::File, InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Resolve Domains File",
                    cmd_template: "puredns resolve {file} -w {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Resolvers Bruteforce",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} -r {file} -w {output_file}",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Rate-Limited Safe Scan",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} --rate-limit 300 -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Skip Wildcard Validation",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} --skip-wildcard-filter -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Quiet Mode Bruteforce",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} -q -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → Subfinder + Resolve",
                    cmd_template: "subfinder -d {domain} -all -silent | puredns resolve -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Aggressive Wildcard Detection",
                    cmd_template: "puredns bruteforce /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain} --wildcard-tests 15 -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
    ],
};