//! Mapping category — 16 tools, 10–12 modes each.
//! Network mapping, port scanning, service detection, infrastructure & technology discovery.
//! Bug fixes: Nmap --json removed, RustScan --json fixed, Masscan --exclude fixed.
//! Wappalyzer replaced with webanalyze.

use super::types::{Category, InputKind, Mode, OutputFormat, Tool};

pub static MAPPING: Category = Category {
    name: "Mapping",
    tools: &[
        // ── HTTPX (Web Probing & Fingerprinting) ─────────────────────────
        Tool {
            name: "HTTPX",
            binary: "httpx-pd",
            modes: &[
                Mode {
                    name: "Live Host Detection",
                    cmd_template: "httpx-pd -u {url} -silent -sc -title -cl -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Technology Fingerprinting",
                    cmd_template: "httpx-pd -u {url} -silent -tech-detect -sc -title -server -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CDN & Server Detection",
                    cmd_template: "httpx-pd -u {url} -silent -cdn -server -sc -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "TLS & CSP Probe",
                    cmd_template: "httpx-pd -u {url} -silent -tls-probe -csp-probe -sc -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JARM Fingerprint",
                    cmd_template: "httpx-pd -u {url} -silent -jarm -sc -title -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Favicon Hash Detection",
                    cmd_template: "httpx-pd -u {url} -silent -favicon -sc -title -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Screenshot Capture",
                    cmd_template: "httpx-pd -u {url} -silent -screenshot -sc -title -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Response Hash Check",
                    cmd_template: "httpx-pd -u {url} -silent -hash -sc -cl -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Port Probe",
                    cmd_template: "httpx-pd -u {url} -silent -ports 80,443,8080,8443,9000,9443,3000,5000 -sc -title -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Full Metadata",
                    cmd_template: "httpx-pd -u {url} -silent -json -o {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Subdomain Probe",
                    cmd_template: "httpx-pd -l {file} -silent -sc -title -tech-detect -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline Full Fingerprint",
                    cmd_template: "httpx-pd -l {file} -silent -sc -title -tech-detect -cdn -server -json -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── DNSX (DNS Resolution & Records) ──────────────────────────────
        Tool {
            name: "DNSX",
            binary: "dnsx",
            modes: &[
                Mode {
                    name: "Comprehensive DNS Resolution",
                    cmd_template: "dnsx -d {domain} -a -aaaa -cname -mx -ns -txt -ptr -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "A/AAAA Record Lookup",
                    cmd_template: "dnsx -d {domain} -a -aaaa -resp-only -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CDN Detection via DNS",
                    cmd_template: "dnsx -d {domain} -a -cdn -cname -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Wildcard Detection",
                    cmd_template: "dnsx -d {domain} -wd -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Reverse PTR Lookup",
                    cmd_template: "dnsx -d {domain} -ptr -resp-only -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SOA & NS Record Query",
                    cmd_template: "dnsx -d {domain} -ns -soa -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "AXFR Zone Transfer Check",
                    cmd_template: "dnsx -d {domain} -axfr -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export All Records",
                    cmd_template: "dnsx -d {domain} -a -cname -mx -ns -txt -silent -json -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Resolve with Rate Limit",
                    cmd_template: "dnsx -l {file} -a -aaaa -silent -o {output_file} -rl 100",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Response Code Filter",
                    cmd_template: "dnsx -d {domain} -a -rcode noerror,servfail -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Naabu (Port Scanner) ─────────────────────────────────────────
        Tool {
            name: "Naabu",
            binary: "naabu",
            modes: &[
                Mode {
                    name: "Top 1000 Port Scan",
                    cmd_template: "naabu -host {ip} -top-ports 1000 -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Full Port Scan (1-65535)",
                    cmd_template: "naabu -host {ip} -p - -rate 1000 -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SYN Scan Mode",
                    cmd_template: "naabu -host {ip} -top-ports 1000 -scan-type s -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Connect Scan Mode",
                    cmd_template: "naabu -host {ip} -top-ports 1000 -scan-type c -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Service Detection Passthrough",
                    cmd_template: "naabu -host {ip} -top-ports 100 -nmap-cli 'nmap -sV' -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Port Range",
                    cmd_template: "naabu -host {ip} -p {ports} -silent -o {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Exclude Ports Scan",
                    cmd_template: "naabu -host {ip} -top-ports 1000 -ep 9100,9200 -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export with Ports",
                    cmd_template: "naabu -host {ip} -top-ports 1000 -json -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CIDR Range Port Scan",
                    cmd_template: "naabu -host {ip}/24 -top-ports 100 -rate 500 -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk IP File Scan",
                    cmd_template: "naabu -list {file} -top-ports 1000 -silent -rate 200 -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Nmap (Advanced Port Scanner & Service Detection) ─────────────
        // NOTE: Nmap does NOT support --json. Use -oX for XML, -oN for normal.
        Tool {
            name: "Nmap",
            binary: "nmap",
            modes: &[
                Mode {
                    name: "Quick TCP Scan",
                    cmd_template: "nmap -T4 -F {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Full TCP Scan (All Ports)",
                    cmd_template: "nmap -sS -p- -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Service & Version Detection",
                    cmd_template: "nmap -sV -sC -O -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "UDP Top Ports Scan",
                    cmd_template: "nmap -sU --top-ports 50 -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Default Script Scan",
                    cmd_template: "nmap -sC -sV -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Vulnerability Script Scan",
                    cmd_template: "nmap --script vuln -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Auth & Brute Scripts",
                    cmd_template: "nmap --script 'auth or brute' -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Discovery Scripts",
                    cmd_template: "nmap --script discovery -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "OS Fingerprint Aggressive",
                    cmd_template: "nmap -A -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "XML Export (Pipeline Ready)",
                    cmd_template: "nmap -sV -sC -T4 -Pn {ip} -oX {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Xml,
                    file_ext: "xml",
                },
                Mode {
                    name: "Host Discovery (Ping Sweep)",
                    cmd_template: "nmap -sn {ip}/24 -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Custom Port + Service Detect",
                    cmd_template: "nmap -sV -p {ports} -T4 -Pn {ip} -oN {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
            ],
        },
        // ── ASNMap (ASN Discovery & CIDR Mapping) ────────────────────────
        Tool {
            name: "ASNMap",
            binary: "asnmap",
            modes: &[
                Mode {
                    name: "Domain ASN Mapping",
                    cmd_template: "asnmap -d {domain} -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Organization ASN Map",
                    cmd_template: "asnmap -org '{value}' -silent -o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP to ASN Mapping",
                    cmd_template: "asnmap -ip {ip} -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "ASN to CIDR Ranges",
                    cmd_template: "asnmap -a {value} -silent -o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export with Metadata",
                    cmd_template: "asnmap -d {domain} -json -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Domain ASN Lookup",
                    cmd_template: "asnmap -df {file} -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → Naabu Scan",
                    cmd_template: "asnmap -d {domain} -silent | naabu -silent -top-ports 100 -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Probe",
                    cmd_template: "asnmap -d {domain} -silent | httpx-pd -silent -sc -title -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Verbose ASN Info",
                    cmd_template: "asnmap -d {domain} -v -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CSV Export",
                    cmd_template: "asnmap -d {domain} -csv -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Csv,
                    file_ext: "csv",
                },
            ],
        },
        // ── TLSX (SSL/TLS Analysis & Certificate Intel) ─────────────────
        Tool {
            name: "TLSX",
            binary: "tlsx",
            modes: &[
                Mode {
                    name: "Comprehensive TLS Analysis",
                    cmd_template: "tlsx -u {domain} -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SSL Certificate Details",
                    cmd_template: "tlsx -u {domain} -silent -so -cn -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "SAN Extraction",
                    cmd_template: "tlsx -u {domain} -silent -san -cn -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JARM TLS Fingerprint",
                    cmd_template: "tlsx -u {domain} -silent -jarm -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Expired Certificate Check",
                    cmd_template: "tlsx -u {domain} -silent -expired -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Self-Signed Certificate Check",
                    cmd_template: "tlsx -u {domain} -silent -self-signed -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "TLS Version Probe",
                    cmd_template: "tlsx -u {domain} -silent -tls-version -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Full Details",
                    cmd_template: "tlsx -u {domain} -silent -json -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Host TLS Scan",
                    cmd_template: "tlsx -l {file} -silent -cn -san -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → Subdomain Discovery",
                    cmd_template: "tlsx -u {domain} -silent -san -resp-only -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── CDNCheck (CDN/WAF Detection) ─────────────────────────────────
        Tool {
            name: "CDNCheck",
            binary: "cdncheck",
            modes: &[
                Mode {
                    name: "CDN Detection (File)",
                    cmd_template: "cdncheck -i {file} -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Single IP CDN Check",
                    cmd_template: "echo {ip} | cdncheck -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CDN Provider JSON",
                    cmd_template: "cdncheck -i {file} -silent -json -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CDN-Only IP Extraction",
                    cmd_template: "cdncheck -i {file} -silent -match-cdn -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Non-CDN IP Discovery",
                    cmd_template: "cdncheck -i {file} -silent -filter-cdn -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "WAF Detection",
                    cmd_template: "cdncheck -i {file} -silent -match-waf -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Cloud Provider Detection",
                    cmd_template: "cdncheck -i {file} -silent -match-cloud -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Single Domain CDN Check",
                    cmd_template: "echo {domain} | cdncheck -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Non-CDN + Non-WAF Filter",
                    cmd_template: "cdncheck -i {file} -silent -filter-cdn -filter-waf -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk CDN Check JSON",
                    cmd_template: "cdncheck -i {file} -silent -json -resp -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── MapCIDR (CIDR/IP Range Manipulation) ─────────────────────────
        Tool {
            name: "MapCIDR",
            binary: "mapcidr",
            modes: &[
                Mode {
                    name: "CIDR to IP List",
                    cmd_template: "echo {ip}/24 | mapcidr -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Bulk CIDR Expansion",
                    cmd_template: "mapcidr -l {file} -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "ASN CIDR Expansion",
                    cmd_template: "echo {value} | mapcidr -silent -o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "CIDR Split into /24s",
                    cmd_template: "echo {ip}/16 | mapcidr -sbc 24 -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Aggregate CIDR Ranges",
                    cmd_template: "mapcidr -l {file} -a -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Count IPs in CIDR",
                    cmd_template: "echo {ip}/24 | mapcidr -c -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Shuffle IP Order",
                    cmd_template: "echo {ip}/24 | mapcidr -shuffle -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Filter by Port",
                    cmd_template: "echo {ip}/24 | mapcidr -shuffle -silent | naabu -p {ports} -silent -o {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Skip Base & Broadcast",
                    cmd_template: "echo {ip}/24 | mapcidr -skip-base -skip-broadcast -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export CIDR Info",
                    cmd_template: "echo {ip}/24 | mapcidr -json -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── Cloudlist (Cloud Asset Discovery) ────────────────────────────
        Tool {
            name: "Cloudlist",
            binary: "cloudlist",
            modes: &[
                Mode {
                    name: "Multi-Cloud Discovery",
                    cmd_template: "cloudlist -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "AWS Resource Enumeration",
                    cmd_template: "cloudlist -provider aws -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Azure Infrastructure Discovery",
                    cmd_template: "cloudlist -provider azure -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "GCP Resource Collection",
                    cmd_template: "cloudlist -provider gcp -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "DigitalOcean Discovery",
                    cmd_template: "cloudlist -provider digitalocean -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Kubernetes Discovery",
                    cmd_template: "cloudlist -provider kubernetes -silent -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Cloud Assets",
                    cmd_template: "cloudlist -silent -json -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "IP-Only Output",
                    cmd_template: "cloudlist -silent -ip -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Host-Only Output",
                    cmd_template: "cloudlist -silent -host -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Probe",
                    cmd_template: "cloudlist -silent | httpx-pd -silent -sc -title -o {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Uncover (OSINT Search Engine Discovery) ──────────────────────
        Tool {
            name: "Uncover",
            binary: "uncover",
            modes: &[
                Mode {
                    name: "Multi-Engine OSINT",
                    cmd_template: "uncover -q {domain} -e shodan,censys,fofa -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Shodan Discovery",
                    cmd_template: "uncover -q {domain} -e shodan -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Censys Discovery",
                    cmd_template: "uncover -q {domain} -e censys -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "FOFA Discovery",
                    cmd_template: "uncover -q {domain} -e fofa -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Hunter Discovery",
                    cmd_template: "uncover -q {domain} -e hunter -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Shodan Dork",
                    cmd_template: "uncover -q '{value}' -e shodan -silent -o {output_file}",
                    inputs: &[InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "IP Range OSINT",
                    cmd_template: "uncover -q net:{ip}/24 -e shodan,censys -silent -o {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export with Sources",
                    cmd_template: "uncover -q {domain} -e shodan,censys,fofa -silent -json -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "All Engines Discovery",
                    cmd_template: "uncover -q {domain} -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → HTTPX Validate",
                    cmd_template: "uncover -q {domain} -e shodan,censys -silent | httpx-pd -silent -sc -title -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── AlterX (Subdomain Permutation Engine) ────────────────────────
        Tool {
            name: "AlterX",
            binary: "alterx",
            modes: &[
                Mode {
                    name: "Default Permutation",
                    cmd_template: "alterx -d {domain} -silent -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Enriched Permutation",
                    cmd_template: "alterx -d {domain} -silent -enrich -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Wordlist Permutation",
                    cmd_template: "alterx -d {domain} -silent -w {file} -o {output_file}",
                    inputs: &[InputKind::Domain, InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Limited Output Permutation",
                    cmd_template: "alterx -d {domain} -silent -limit 1000 -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom Pattern Permutation",
                    cmd_template: "alterx -d {domain} -silent -p '{value}' -o {output_file}",
                    inputs: &[InputKind::Domain, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export Permutations",
                    cmd_template: "alterx -d {domain} -silent -json -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk Domain Permutation",
                    cmd_template: "alterx -l {file} -silent -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → PureDNS Resolve",
                    cmd_template: "alterx -d {domain} -silent -enrich | puredns resolve -w {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Pipeline → DNSX Resolve",
                    cmd_template: "alterx -d {domain} -silent -enrich | dnsx -silent -a -resp -o {output_file}",
                    inputs: &[InputKind::Domain],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Stdin Permutation",
                    cmd_template: "cat {file} | alterx -silent -enrich -o {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── WhatWeb (Web Technology Fingerprinting) ──────────────────────
        Tool {
            name: "WhatWeb",
            binary: "whatweb",
            modes: &[
                Mode {
                    name: "Aggressive Fingerprint",
                    cmd_template: "whatweb -a 3 {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Stealthy Passive Scan",
                    cmd_template: "whatweb -a 1 {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Verbose Output",
                    cmd_template: "whatweb -a 3 -v {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "JSON Export",
                    cmd_template: "whatweb -a 3 --log-json={output_file} {url}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "XML Export",
                    cmd_template: "whatweb -a 3 --log-xml={output_file} {url}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Xml,
                    file_ext: "xml",
                },
                Mode {
                    name: "Bulk URL File Scan",
                    cmd_template: "whatweb -i {file} -a 3 | tee {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Custom User-Agent Scan",
                    cmd_template: "whatweb -a 3 --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Proxy-Enabled Scan",
                    cmd_template: "whatweb -a 3 --proxy http://127.0.0.1:8080 {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Max Threads Scan",
                    cmd_template: "whatweb -a 3 --max-threads 25 {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Follow Redirects Deep",
                    cmd_template: "whatweb -a 3 --follow-redirect=always {url} | tee {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── Webanalyze (Technology Detection — Wappalyzer Engine) ────────
        // Replaces wappalyzer-cli with actively maintained Go-based alternative.
        Tool {
            name: "Webanalyze",
            binary: "webanalyze",
            modes: &[
                Mode {
                    name: "Technology Detection",
                    cmd_template: "webanalyze -host {url} -output json > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Crawl + Detect",
                    cmd_template: "webanalyze -host {url} -crawl 3 -output json > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Batch URL File Scan",
                    cmd_template: "webanalyze -hosts {file} -output json > {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CSV Export Results",
                    cmd_template: "webanalyze -host {url} -output csv > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Csv,
                    file_ext: "csv",
                },
                Mode {
                    name: "Update Technologies DB",
                    cmd_template: "webanalyze -update && echo 'Database updated' > {output_file}",
                    inputs: &[],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Concurrent Workers Scan",
                    cmd_template: "webanalyze -host {url} -workers 8 -output json > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Silent Mode Scan",
                    cmd_template: "webanalyze -host {url} -silent -output json > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Apps File",
                    cmd_template: "webanalyze -host {url} -apps {file} -output json > {output_file}",
                    inputs: &[InputKind::Url, InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Pipeline HTTPX → Detect",
                    cmd_template: "httpx-pd -l {file} -silent | xargs -I{{}} webanalyze -host {{}} -output json >> {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Redirect Follow Scan",
                    cmd_template: "webanalyze -host {url} -redirect -output json > {output_file}",
                    inputs: &[InputKind::Url],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── Masscan (Mass IP Port Scanner) ───────────────────────────────
        // NOTE: --exclude is for IPs, --excludeports is for ports.
        Tool {
            name: "Masscan",
            binary: "masscan",
            modes: &[
                Mode {
                    name: "Full TCP Port Scan",
                    cmd_template: "masscan {ip} -p1-65535 --rate 10000 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Top Web Ports",
                    cmd_template: "masscan {ip} -p80,443,8080,8443,8000,3000,5000,9000,9443 --rate 10000 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Banner Grab Mode",
                    cmd_template: "masscan {ip} -p80,443,8080,8443 --banners --rate 1000 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "CIDR Range Scan",
                    cmd_template: "masscan {ip}/24 -p80,443,8080 --rate 10000 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Port Range",
                    cmd_template: "masscan {ip} -p{ports} --rate 10000 -oJ {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Exclude Ports Scan",
                    cmd_template: "masscan {ip} -p1-65535 --rate 10000 --excludeports 9100,9200 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "XML Export",
                    cmd_template: "masscan {ip} -p1-1000 --rate 10000 -oX {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Xml,
                    file_ext: "xml",
                },
                Mode {
                    name: "Source IP Scan",
                    cmd_template: "masscan {ip} -p1-65535 --rate 10000 --source-ip {value} -oJ {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk IP File Scan",
                    cmd_template: "masscan -iL {file} -p80,443,8080 --rate 10000 -oJ {output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Rate-Limited Safe Scan",
                    cmd_template: "masscan {ip} -p1-65535 --rate 1000 -oJ {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
        // ── RustScan (Fast Port Scanner + Nmap Integration) ─────────────
        // NOTE: RustScan has no --json flag. Use -g for greppable or pipe nmap.
        Tool {
            name: "RustScan",
            binary: "rustscan",
            modes: &[
                Mode {
                    name: "Fast Port Scan",
                    cmd_template: "rustscan -a {ip} -- -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Service Version Detection",
                    cmd_template: "rustscan -a {ip} -- -sV -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Script + Version Scan",
                    cmd_template: "rustscan -a {ip} -- -sC -sV -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Custom Port Range",
                    cmd_template: "rustscan -a {ip} -p {ports} -- -sV -oN {output_file}",
                    inputs: &[InputKind::Ip, InputKind::Ports],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Batch Size Control",
                    cmd_template: "rustscan -a {ip} -b 500 -- -sV -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Greppable Output",
                    cmd_template: "rustscan -a {ip} -g 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
                Mode {
                    name: "Aggressive Full Scan",
                    cmd_template: "rustscan -a {ip} -- -A -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Custom Timeout Scan",
                    cmd_template: "rustscan -a {ip} --timeout 3000 -- -sV -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Top Ports Only",
                    cmd_template: "rustscan -a {ip} --top -- -sV -oN {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Nmap,
                    file_ext: "nmap",
                },
                Mode {
                    name: "Accessible Mode (No Nmap)",
                    cmd_template: "rustscan -a {ip} --accessible 2>&1 | tee {output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Lines,
                    file_ext: "txt",
                },
            ],
        },
        // ── ZGrab2 (Application Layer Banner Grabbing) ───────────────────
        Tool {
            name: "ZGrab2",
            binary: "zgrab2",
            modes: &[
                Mode {
                    name: "HTTP Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 http -p 80 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "HTTPS Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 http -p 443 --use-https --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "SSH Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 ssh -p 22 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "TLS Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 tls -p 443 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "SMTP Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 smtp -p 25 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "FTP Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 ftp -p 21 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "MySQL Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 mysql -p 3306 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Redis Banner Grab",
                    cmd_template: "echo {ip} | zgrab2 redis -p 6379 --output-file={output_file}",
                    inputs: &[InputKind::Ip],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Custom Module Grab",
                    cmd_template: "echo {ip} | zgrab2 {value} --output-file={output_file}",
                    inputs: &[InputKind::Ip, InputKind::Custom("Value", "value")],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
                Mode {
                    name: "Bulk IP Banner Grab",
                    cmd_template: "zgrab2 http --input-file={file} --output-file={output_file}",
                    inputs: &[InputKind::File],
                    output_format: OutputFormat::Json,
                    file_ext: "json",
                },
            ],
        },
    ],
};